WIP: Unit test fixes
j5int/processfamily pull request #28
Opened 2022-09-15 07:16 UTC by grahamm-hexagon

WIP changes for unit-test

2022-09-19 10:13 UTC, yaseen-mowzer-hexagon commented
I just want to double check that we only made changes to the tests. There were no changes to the actual ProcessFamily necessary?

2022-09-19 10:14 UTC, yaseen-mowzer-hexagon commented
Can you add a summary of your analysis (e.g. which tests are failing and why that is okay) in the pull request description?

2022-09-19 10:27 UTC, yaseen-mowzer-hexagon requested changes

2022-09-19 10:27 UTC, yaseen-mowzer-hexagon commented on processfamily/test_processfamily.py
> +            # so frequently that they are still in a STOP_WAIT state when I get here
Can you delete the part of the comment that reference windows and linux. I think that just makes it confusing.

2022-09-20 06:18 UTC, grahamm-hexagon commented
> 

correct

2022-09-20 06:26 UTC, grahamm-hexagon commented
Adding this as a comment.
The following tests are failing.
When running the testcases individually the Windows service tests are failing when testing with a different user.  This appears to be environmental.
When testing some of the startup edge cases, the tests do not count the number of terminated processes correctly.

2022-09-20 07:20 UTC, yaseen-mowzer-hexagon approved these changes

2022-09-20 07:21 UTC, merged

2022-09-20 07:25 UTC, yaseen-mowzer-hexagon commented
From our internal JIRA ticket, this is what tests are failing:
```
test_processfamily.py::TestFunkyWebServer::test_parent_stop_child_locked_up[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_parent_exit_child_locked_up[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_parent_kill_child_locked_up[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_child_exit_on_start[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_child_error_during_run[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_child_freeze_on_start[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_child_error_on_start[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_child_error_during_init[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_child_freeze_during_init[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_child_crash_on_start[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_file_open_by_parent_before_fork_can_be_closed_and_deleted[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_echo_std_err_on[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_handles_over_commandline_off[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_handles_over_commandline_off_close_fds_off[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_close_fds_off[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_child_comms_strategy_stdin_close[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_child_comms_strategy_none[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_child_comms_strategy_signal[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_use_job_object_off[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_cpu_affinity_off[windows_service-None]
test_processfamily.py::TestFunkyWebServer::test_handles_over_commandline_off_file_open_by_parent[windows_service-None]
test_processfamily.py::TestWindowsService::test_service_stop[None]
test_processfamily.py::TestWindowsService::test_service_stop_child_locked_up[None]
test_processfamily.py::TestWindowsService::test_service_stop_child_freeze_on_start[None]
test_processfamily.py::TestFunkyWebServer::test_parent_stop[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_parent_exit[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_parent_stop_child_locked_up[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_parent_exit_child_locked_up[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_child_exit_on_start[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_child_error_during_run[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_child_freeze_on_start[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_child_error_on_start[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_child_error_during_init[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_child_freeze_during_init[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_child_crash_on_start[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_file_open_by_parent_before_fork_can_be_closed_and_deleted[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_echo_std_err_on[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_handles_over_commandline_off[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_handles_over_commandline_off_close_fds_off[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_close_fds_off[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_child_comms_strategy_stdin_close[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_child_comms_strategy_none[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_child_comms_strategy_signal[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_use_job_object_off[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_cpu_affinity_off[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_handles_over_commandline_off_file_open_by_parent[windows_service-NT AUTHORITY\NetworkService]
test_processfamily.py::TestWindowsService::test_service_stop[NT AUTHORITY\NetworkService]
test_processfamily.py::TestWindowsService::test_service_stop_child_locked_up[NT AUTHORITY\NetworkService]
test_processfamily.py::TestWindowsService::test_service_stop_child_freeze_on_start[NT AUTHORITY\NetworkService]
test_processfamily.py::TestFunkyWebServer::test_child_freeze_on_start[normal_subprocess]
test_processfamily.py::TestFunkyWebServer::test_child_freeze_on_start[pythonw]
test_processfamily.py::TestFunkyWebServer::test_child_freeze_during_init[normal_subprocess]
test_processfamily.py::TestFunkyWebServer::test_child_freeze_during_init[pythonw]
```